apiVersion: rbac.authorizarion.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod_role_bind
  namespace: RBAC_Namespace
subjects:
  kind: Service Account
  name: my-servieaccount
  namespace: RBAC_Namespace
roleRef:
  kind: Role
  name: RBAC_Role
  apiGroups: rbac.authorization.k8s.io
  
